    <aside role='complementary' class="secondary">
			<div class="widget widget_narrow highlight highlight_tertiary">
				<p>Log in with your staff account to include secure documents in your search.</p>
				<a href="" class="button secondary">Log in</a>
			</div>

			<div class="widget widget_narrow highlight highlight_tertiary">
				<p>You are logged in as <strong>Jane Bloggs</strong> (<code>bloggsja</code>).</p>
				<a href="" class="button secondary">Log out</a>
			</div>

    	<div id="search-facets">
            <h2 id="search_filters">Narrow your search </h2>
            
				<h3 class='toggle active'>Search for... <span class='ui_toggle_arrow'></span></h3>
				<ul class="toggle_block active facet_links">
					<li><a href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;q=doctor&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;site=web_collection" class="selected">Webpages</a></li>
					<li><a href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;q=doctor&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;site=vicphones_collection">People</a></li>
					<li><a href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;q=doctor&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;site=docs_collection">Documents</a></li>
				</ul>
				<h3 class='toggle'>File type <span class='ui_toggle_arrow'></span></h3>
				<ul class="toggle_block facet_links">
					<li><a href="search?q=doctor+ext%3Axls+OR+ext%3Axlsx&amp;client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1">Microsoft Excel</a></li>
					<li><a href="search?q=doctor+ext%3Apdf&amp;client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1">PDF</a></li>
					<li><a href="search?q=doctor+ext%3Appt+OR+ext%3Apptx&amp;client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1">Microsoft PowerPoint</a></li>
					<li><a href="search?q=doctor+ext%3Adoc+OR+ext%3Adocx+OR+ext%3Adocm+OR+ext%3Adot&amp;client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1">Microsoft Word</a></li>
					<li><a href="search?">This is<!-- a really long facet stretching onto two lines--></a></li>
					<li><a href="search?" class="button primary">Button</a></li>

				
				</ul>
				<h3 class='toggle'>Author <span class='ui_toggle_arrow'></span></h3>
				<div class="toggle_block">
					<ul id="author-list" class="facet_links">
					<!-- have to move spans inside links for tag styling to work on mobile -->
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Victoria%2520Business%2520School&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Victoria%2520Business%2520School" title="Victoria Business School">Victoria Business School <span class="dn-attr-c"> (80)</span></a></li>
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington" title="Victoria University of Wellington">Victoria University of Wellington <span class="dn-attr-c"> (69)</span></a></li>
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce%252E%2520School%2520of%2520Management&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce%252E%2520School%2520of%2520Management" title="School of Management">School of Management <span class="dn-attr-c"> (52)</span></a></li>
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Law&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Law" title="Faculty of Law">Faculty of Law <span class="dn-attr-c"> (45)</span></a></li>
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce%252E%2520School%2520of%2520Government&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce%252E%2520School%2520of%2520Government" title="School of Government">School of Government <span class="dn-attr-c"> (44)</span></a></li>
						<li><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Antarctic%2520Research%2520Centre&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Antarctic%2520Research%2520Centre" title="Antarctic Research Centre">Antarctic Research Centre</a><span class="dn-attr-c"> (36)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Education&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Education" title="Faculty of Education">Faculty of Education</a><span class="dn-attr-c"> (26)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Science&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Science" title="Faculty of Science">Faculty of Science</a><span class="dn-attr-c"> (26)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Science%252E%2520School%2520of%2520Psychology&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Science%252E%2520School%2520of%2520Psychology" title="School of Psychology">School of Psychology</a><span class="dn-attr-c"> (18)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Graduate%2520Research&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Graduate%2520Research" title="Faculty of Graduate Research">Faculty of Graduate Research</a><span class="dn-attr-c"> (13)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Commerce" title="Faculty of Commerce">Faculty of Commerce</a><span class="dn-attr-c"> (11)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Humanities%2520and%2520Social%2520Sciences&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Humanities%2520and%2520Social%2520Sciences" title="Faculty of Humanities and Social Sciences">Faculty of Humanities and Social Sciences</a><span class="dn-attr-c"> (11)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Architecture%2520and%2520Design&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Architecture%2520and%2520Design" title="Faculty of Architecture and Design">Faculty of Architecture and Design</a><span class="dn-attr-c"> (5)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBailey%252C%2520John%2520Patrick%2520Macarthur&amp;dnavs=inmeta:DC%252Ecreator%3DBailey%252C%2520John%2520Patrick%2520Macarthur" title="Bailey, John Patrick Macarthur">Bailey, John Patrick Macarthur</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBandyopadhyay%252C%2520Sekhar&amp;dnavs=inmeta:DC%252Ecreator%3DBandyopadhyay%252C%2520Sekhar" title="Bandyopadhyay, Sekhar">Bandyopadhyay, Sekhar</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBarone%252C%2520Susan%2520Marie&amp;dnavs=inmeta:DC%252Ecreator%3DBarone%252C%2520Susan%2520Marie" title="Barone, Susan Marie">Barone, Susan Marie</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBell%252C%2520Lara%2520Joyce%2520Milka&amp;dnavs=inmeta:DC%252Ecreator%3DBell%252C%2520Lara%2520Joyce%2520Milka" title="Bell, Lara Joyce Milka">Bell, Lara Joyce Milka</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBell%252C%2520Marie&amp;dnavs=inmeta:DC%252Ecreator%3DBell%252C%2520Marie" title="Bell, Marie">Bell, Marie</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBrown%252C%2520Denzil%2520J%252E&amp;dnavs=inmeta:DC%252Ecreator%3DBrown%252C%2520Denzil%2520J%252E" title="Brown, Denzil J.">Brown, Denzil J.</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DBryson%252C%2520Jane%2520Elspeth&amp;dnavs=inmeta:DC%252Ecreator%3DBryson%252C%2520Jane%2520Elspeth" title="Bryson, Jane Elspeth">Bryson, Jane Elspeth</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DDavidson%252C%2520Raewyn%2520Anita&amp;dnavs=inmeta:DC%252Ecreator%3DDavidson%252C%2520Raewyn%2520Anita" title="Davidson, Raewyn Anita">Davidson, Raewyn Anita</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DHammond%252C%2520Brady&amp;dnavs=inmeta:DC%252Ecreator%3DHammond%252C%2520Brady" title="Hammond, Brady">Hammond, Brady</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DHarper%252C%2520Elinore&amp;dnavs=inmeta:DC%252Ecreator%3DHarper%252C%2520Elinore" title="Harper, Elinore">Harper, Elinore</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DHunter%252C%2520Mark%2520Warwick&amp;dnavs=inmeta:DC%252Ecreator%3DHunter%252C%2520Mark%2520Warwick" title="Hunter, Mark Warwick">Hunter, Mark Warwick</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DHuntington%252C%2520Annette%2520Diana&amp;dnavs=inmeta:DC%252Ecreator%3DHuntington%252C%2520Annette%2520Diana" title="Huntington, Annette Diana">Huntington, Annette Diana</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DKolodziej%252C%2520Andrew%2520Peter&amp;dnavs=inmeta:DC%252Ecreator%3DKolodziej%252C%2520Andrew%2520Peter" title="Kolodziej, Andrew Peter">Kolodziej, Andrew Peter</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DLa%2520Pine%252C%2520Mary%2520Patricia&amp;dnavs=inmeta:DC%252Ecreator%3DLa%2520Pine%252C%2520Mary%2520Patricia" title="La Pine, Mary Patricia">La Pine, Mary Patricia</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DMackle%252C%2520Diane%2520Margaret&amp;dnavs=inmeta:DC%252Ecreator%3DMackle%252C%2520Diane%2520Margaret" title="Mackle, Diane Margaret">Mackle, Diane Margaret</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DMaude%252C%2520Robyn%2520Mary&amp;dnavs=inmeta:DC%252Ecreator%3DMaude%252C%2520Robyn%2520Mary" title="Maude, Robyn Mary">Maude, Robyn Mary</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DPierce%252C%2520Hannah&amp;dnavs=inmeta:DC%252Ecreator%3DPierce%252C%2520Hannah" title="Pierce, Hannah">Pierce, Hannah</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DQuirke%252C%2520Sara%2520Jane%2520Michaela&amp;dnavs=inmeta:DC%252Ecreator%3DQuirke%252C%2520Sara%2520Jane%2520Michaela" title="Quirke, Sara Jane Michaela">Quirke, Sara Jane Michaela</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DRowse%252C%2520Helen%2520Jane&amp;dnavs=inmeta:DC%252Ecreator%3DRowse%252C%2520Helen%2520Jane" title="Rowse, Helen Jane">Rowse, Helen Jane</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DRyder%252DLewis%252C%2520Michelle&amp;dnavs=inmeta:DC%252Ecreator%3DRyder%252DLewis%252C%2520Michelle" title="Ryder-Lewis, Michelle">Ryder-Lewis, Michelle</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DRyton%252DMalden%252C%2520Tara%2520Marie&amp;dnavs=inmeta:DC%252Ecreator%3DRyton%252DMalden%252C%2520Tara%2520Marie" title="Ryton-Malden, Tara Marie">Ryton-Malden, Tara Marie</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DSasagi%252C%2520Fiona&amp;dnavs=inmeta:DC%252Ecreator%3DSasagi%252C%2520Fiona" title="Sasagi, Fiona">Sasagi, Fiona</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DSedley%252C%2520Benjamin%2520Peter&amp;dnavs=inmeta:DC%252Ecreator%3DSedley%252C%2520Benjamin%2520Peter" title="Sedley, Benjamin Peter">Sedley, Benjamin Peter</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DSlack%252C%2520Adrian&amp;dnavs=inmeta:DC%252Ecreator%3DSlack%252C%2520Adrian" title="Slack, Adrian">Slack, Adrian</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DSquires%252C%2520Keryn&amp;dnavs=inmeta:DC%252Ecreator%3DSquires%252C%2520Keryn" title="Squires, Keryn">Squires, Keryn</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DTong%252C%2520Wendy%2520Yee&amp;dnavs=inmeta:DC%252Ecreator%3DTong%252C%2520Wendy%2520Yee" title="Tong, Wendy Yee">Tong, Wendy Yee</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520Business%2520School&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520Business%2520School" title="Victoria Business School">Victoria Business School</a><span class="dn-attr-c"> (1)</span></li>
						<li class="facet-hidden"><a class="dn-attr-v" href="/search?client=vuw_frontend&amp;output=xml_no_dtd&amp;proxystylesheet=vuw_frontend&amp;ie=UTF-8&amp;oe=UTF-8&amp;getfields=*&amp;filter=p&amp;site=default_collection&amp;btnG=&amp;ip=130.195.90.121&amp;access=p&amp;sort=date:D:L:d1&amp;entqr=3&amp;entqrm=0&amp;entsp=a&amp;ud=1&amp;q=doctor+inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Engineering&amp;dnavs=inmeta:DC%252Ecreator%3DVictoria%2520University%2520of%2520Wellington%252E%2520Faculty%2520of%2520Engineering" title="Faculty of Engineering">Faculty of Engineering</a><span class="dn-attr-c"> (1)</span></li>
					</ul>
					<a class="show_more button tertiary">Show More</a>
				</div>
				
			
		</div>
    </aside>

